import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { etb, fmtDateTime } from "./format";

const EM = [6, 95, 70] as [number, number, number];
const MINT = [167, 243, 208] as [number, number, number];

function header(doc: jsPDF, title: string, sub: string) {
  doc.setFillColor(...EM);
  doc.rect(0, 0, 210, 34, "F");
  doc.setTextColor(...MINT);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("SAPPY LEGACY", 14, 16);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("INVENTORY  /  FINANCE", 14, 22);
  doc.setTextColor(255, 248, 231);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(title, 14, 30);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(sub, 210 - 14, 30, { align: "right" });
  doc.setTextColor(20, 20, 20);
}

function footer(doc: jsPDF) {
  const y = doc.internal.pageSize.getHeight() - 10;
  doc.setDrawColor(...MINT);
  doc.line(14, y - 3, 196, y - 3);
  doc.setFontSize(7.5);
  doc.setTextColor(120, 120, 120);
  doc.text("Generated by Sappy Legacy  -  " + new Date().toLocaleString("en-GB"), 14, y);
}

type SaleRow = { createdAt: string; saleNo: string; itemName: string; serial: string; quantity: number; unitPrice: number; discount: number; total: number };

export function downloadSalesReportPdf(title: string, rangeLabel: string, rows: SaleRow[], grandTotal: number) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  header(doc, title, rangeLabel);
  autoTable(doc, {
    startY: 42,
    head: [["Date / Time", "Sale #", "Item", "Serial", "Qty", "Unit", "Discount", "Total"]],
    body: rows.length ? rows.map((r) => [fmtDateTime(r.createdAt), r.saleNo, r.itemName, r.serial || "-", String(r.quantity), etb(r.unitPrice), etb(r.discount), etb(r.total)]) : [["", "", "No sales in this period", "", "", "", "", ""]],
    styles: { fontSize: 8, cellPadding: 2.5, textColor: [30, 30, 30] },
    headStyles: { fillColor: EM, textColor: MINT, fontStyle: "bold", fontSize: 8 },
    alternateRowStyles: { fillColor: [255, 248, 231] },
    columnStyles: { 4: { halign: "right" }, 5: { halign: "right" }, 6: { halign: "right" }, 7: { halign: "right", fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  const y = (doc as any).lastAutoTable.finalY + 8;
  doc.setFillColor(...EM);
  doc.roundedRect(140, y, 56, 12, 2, 2, "F");
  doc.setTextColor(...MINT);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("TOTAL  " + etb(grandTotal), 193, y + 8, { align: "right" });
  doc.setTextColor(20, 20, 20);
  footer(doc);
  doc.save(`${title.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.pdf`);
}

type PoLine = { description: string; quantity: number; unitCost: number };
type Po = { poNo: string; createdAt: string; supplier: string; status: string; note: string | null; lines: PoLine[]; totalCost: number };

export function downloadPurchaseOrderPdf(po: Po) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  header(doc, "PURCHASE ORDER", po.poNo);
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.text(`Date: ${fmtDateTime(po.createdAt)}`, 14, 44);
  doc.text(`Status: ${po.status.toUpperCase()}`, 14, 50);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...EM);
  doc.text("Supplier:", 14, 60);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(20, 20, 20);
  doc.text(String(po.supplier), 40, 60);
  autoTable(doc, {
    startY: 68,
    head: [["#", "Description", "Qty", "Unit Cost (ETB)", "Line Total (ETB)"]],
    body: po.lines.map((l, i) => [String(i + 1), l.description, String(l.quantity), etb(l.unitCost), etb(l.quantity * l.unitCost)]),
    styles: { fontSize: 9, cellPadding: 3, textColor: [30, 30, 30] },
    headStyles: { fillColor: EM, textColor: MINT, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [255, 248, 231] },
    columnStyles: { 2: { halign: "right" }, 3: { halign: "right" }, 4: { halign: "right", fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  const y = (doc as any).lastAutoTable.finalY + 8;
  doc.setFillColor(...EM);
  doc.roundedRect(140, y, 56, 12, 2, 2, "F");
  doc.setTextColor(...MINT);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("TOTAL  " + etb(po.totalCost), 193, y + 8, { align: "right" });
  if (po.note) {
    doc.setTextColor(80, 80, 80);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8.5);
    doc.text("Note: " + po.note, 14, y + 22, { maxWidth: 182 });
  }
  doc.setTextColor(20, 20, 20);
  doc.setDrawColor(...MINT);
  doc.line(14, 250, 80, 250);
  doc.line(130, 250, 196, 250);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("Authorized by", 14, 254);
  doc.text("Supplier signature", 130, 254);
  footer(doc);
  doc.save(`po-${po.poNo.toLowerCase()}.pdf`);
}